# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Wildcards Raid Team
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation and guides for the World of Warcraft raid team,
  the Wildcards. Part of the Currently Offline guild on the US
  server, Sargeras.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://teamwildcards.com" # the base hostname & protocol for your site, e.g. http://example.com
guild_url: "http://coguild.com"
raid_team_name: Wildcards
site_admin_name: tacofish
guild_name: Currently Offline

#defaults
collections:
  Policies:
    output: true
    permalink: /:collection/:path/:title
  Raiding:
    output: true
    permalink: /:collection/:path/:title
  Classes:
    output: true
    permalink: /:collection/:path/:title
  Tips:
    output: true
    permalink: /:collection/:path/:title

# Build settings
markdown: kramdown
theme:

sass:
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets
gems:
  - jekyll-feed
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
